### ISSUE TITLE
Grafana not picking up data in InfluxDB

### ISSUE THREAD

**Issue by C-monC** [jonas-werner/EdgeX_Tutorial#4]
Hi Jonas,

In the last section of your tutorial after linking Grafana to the influxDB database I am struggling to get the data to show.

Running `http://195.168.1.5:48080/api/v1/reading` shows that the python script sending data is indeed working.

In Grafana's interface the db links successfully but it seems like influxdb is not being populated. I am also certain the Grafana query is correct (copied the strings from the above request). Is there a way for me to check the influxdb contents? It also seems like at no stage I directly linked the influxdb docker with the other dockers - is this automatically done by the docker-compose?

I've checked the InfluxDB docker and the db sensordata is not being populated. 

Kind regards,
Simon

**Comment by C-monC** [comment]
The issue was in the eclipse-mosquitto docker. It failed to start the broker. Running a mosquitto broker in the virtualbox fixed all the issues.

**Comment by jonas-werner** [comment]
Thanks for letting me know!
